"""Task loaders.

Public functions:
    load_humaneval(n=None, contexts=...)  -> list[Task]
    load_swebench_lite(n=None)            -> list[Task]    (optional, requires HF auth)
    build_controlled_context_suite(...)   -> list[Task]    (custom H1 contexts)
    build_synthetic_tool_use_suite(n=50)  -> list[Task]    (procedural; described in §3.2)

The HumanEval loader supports the article's "context inflation" trick from E1
and E3: each task is wrapped with ``context_target_tokens`` of plausible
historical project context (other-task code, docstrings, comments) so that the
*shared context* C0 dominates token cost — exactly the regime in which H1
predicts a Hybrid-INoT advantage.
"""
from __future__ import annotations

import gzip
import json
import random
from typing import Optional
import urllib.request

from ..config import project_root
from ..llm import count_tokens
from ..types import Task

_DATA_DIR = project_root() / "data"
_CACHE_DIR = _DATA_DIR / "cache"
_CACHE_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# HumanEval (Chen et al. 2021)
# ---------------------------------------------------------------------------
_HUMANEVAL_JSON = _DATA_DIR / "humaneval.jsonl"


def _ensure_humaneval() -> list[dict]:
    """Download HumanEval once into ``data/humaneval.jsonl``."""
    if _HUMANEVAL_JSON.exists():
        return [
            json.loads(line)
            for line in _HUMANEVAL_JSON.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
    # Try huggingface datasets first (cleanest source)
    try:
        from datasets import load_dataset  # type: ignore
        ds = load_dataset("openai_humaneval", split="test")
        rows = [
            {
                "task_id": r["task_id"],
                "prompt": r["prompt"],
                "test": r["test"],
                "entry_point": r["entry_point"],
                "canonical_solution": r["canonical_solution"],
            }
            for r in ds
        ]
    except Exception:  # pragma: no cover - network
        # Fallback: direct GitHub raw URL
        url = "https://raw.githubusercontent.com/openai/human-eval/master/data/HumanEval.jsonl.gz"
        with urllib.request.urlopen(url) as r:
            blob = r.read()
        rows = [
            json.loads(line)
            for line in gzip.decompress(blob).decode("utf-8").splitlines()
            if line.strip()
        ]
        rows = [
            {
                "task_id": r["task_id"],
                "prompt": r["prompt"],
                "test": r["test"],
                "entry_point": r["entry_point"],
                "canonical_solution": r["canonical_solution"],
            }
            for r in rows
        ]
    _HUMANEVAL_JSON.write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in rows), encoding="utf-8"
    )
    return rows


def load_humaneval(
    n: Optional[int] = None,
    *,
    context_target_tokens: int = 0,
    seed: int = 42,
) -> list[Task]:
    """Return ``n`` HumanEval tasks (deterministic order).

    If ``context_target_tokens > 0`` each task is wrapped with that many tokens
    of synthetic "project history" sampled from the other HumanEval prompts.
    This realises the E1/E3 protocol (versions of length {512, 2048, 8192}).
    """
    rows = _ensure_humaneval()
    rng = random.Random(seed)
    selected = rows if n is None else rows[: n]
    pool = [r for r in rows if r not in selected] or rows
    tasks: list[Task] = []
    for r in selected:
        ctx = (
            _build_synthetic_context(pool, target_tokens=context_target_tokens, rng=rng)
            if context_target_tokens > 0
            else ""
        )
        tasks.append(
            Task(
                task_id=f"{r['task_id']}@ctx{context_target_tokens}",
                prompt=r["prompt"],
                context=ctx,
                test_code=r["test"],
                entry_point=r["entry_point"],
                suite="humaneval",
                metadata={
                    "context_target_tokens": context_target_tokens,
                    "context_actual_tokens": count_tokens(ctx),
                    "canonical_solution": r["canonical_solution"],
                    "original_id": r["task_id"],
                },
            )
        )
    return tasks


def _build_synthetic_context(pool: list[dict], target_tokens: int, rng: random.Random) -> str:
    """Concatenate prompts/solutions from other tasks until token budget is hit.

    The article's E1 protocol calls for 'historical context generated by a
    deterministic template'; using sibling HumanEval items keeps the textual
    distribution realistic (Python code + docstrings) without leaking the
    target task's solution.
    """
    pieces: list[str] = []
    used = 0
    items = list(pool)
    rng.shuffle(items)
    i = 0
    while used < target_tokens and i < len(items):
        r = items[i]
        i += 1
        block = (
            "# --- legacy project module ---\n"
            f"# {r['task_id']}\n"
            f"{r['prompt']}\n"
            f"{r['canonical_solution']}\n"
            "# --- end module ---\n\n"
        )
        pieces.append(block)
        used += count_tokens(block)
        if i == len(items):  # wrap around if needed
            i = 0
            rng.shuffle(items)
    return "".join(pieces)


# ---------------------------------------------------------------------------
# Controlled Context Suite (custom H1 benchmark)
# ---------------------------------------------------------------------------
def build_controlled_context_suite(
    n: int = 50,
    *,
    context_target_tokens: int = 2048,
    seed: int = 42,
) -> list[Task]:
    """Build deterministic Python tasks with controlled irrelevant context.

    HumanEval is realistic but not perfectly controlled: different tasks carry
    different prompt lengths and hidden difficulty. This suite isolates the H1
    variable by holding task families fixed while scaling only ``|C0|``.
    Context blocks are decoys and API notes that never contain the target
    solution, so compression/token effects can be tested without leakage.
    """
    rng = random.Random(seed)
    templates = [_controlled_reverse_words, _controlled_count_peaks, _controlled_normalize_path]
    tasks: list[Task] = []
    for i in range(n):
        task = templates[i % len(templates)](i, rng)
        ctx = _controlled_context(task.entry_point, context_target_tokens, rng)
        task.context = ctx
        task.task_id = f"{task.task_id.rsplit('@ctx', 1)[0]}@ctx{context_target_tokens}"
        task.metadata.update({
            "context_target_tokens": context_target_tokens,
            "context_actual_tokens": count_tokens(ctx),
            "controlled_family": task.metadata.get("family", ""),
        })
        tasks.append(task)
    return tasks


def _controlled_reverse_words(i: int, rng: random.Random) -> Task:
    entry = f"solve_reverse_words_{i}"
    return Task(
        task_id=f"controlled/reverse_words/{i}@ctx0",
        prompt=(
            f"Implement `{entry}(text: str) -> str`. Split the input on whitespace, "
            "reverse every word individually, and join the words back with a single space."
        ),
        context="",
        test_code=(
            "def check(candidate):\n"
            "    assert candidate('abc de') == 'cba ed'\n"
            "    assert candidate('  one   two ') == 'eno owt'\n"
            "    assert candidate('') == ''\n"
        ),
        entry_point=entry,
        suite="controlled_context",
        metadata={"family": "reverse_words", "difficulty_seed": rng.randint(0, 10_000)},
    )


def _controlled_count_peaks(i: int, rng: random.Random) -> Task:
    entry = f"solve_count_peaks_{i}"
    return Task(
        task_id=f"controlled/count_peaks/{i}@ctx0",
        prompt=(
            f"Implement `{entry}(values: list[int]) -> int`. Count positions i where "
            "values[i] is strictly greater than both direct neighbours."
        ),
        context="",
        test_code=(
            "def check(candidate):\n"
            "    assert candidate([1, 3, 2, 4, 1]) == 2\n"
            "    assert candidate([5, 4, 3]) == 0\n"
            "    assert candidate([1, 2, 3, 2, 1, 2, 1]) == 2\n"
            "    assert candidate([]) == 0\n"
        ),
        entry_point=entry,
        suite="controlled_context",
        metadata={"family": "count_peaks", "difficulty_seed": rng.randint(0, 10_000)},
    )


def _controlled_normalize_path(i: int, rng: random.Random) -> Task:
    entry = f"solve_normalize_path_{i}"
    return Task(
        task_id=f"controlled/normalize_path/{i}@ctx0",
        prompt=(
            f"Implement `{entry}(path: str) -> str`. Normalize a Unix-like path by "
            "removing empty segments and '.', resolving '..', and returning a path "
            "that always starts with '/'."
        ),
        context="",
        test_code=(
            "def check(candidate):\n"
            "    assert candidate('/a//b/./c') == '/a/b/c'\n"
            "    assert candidate('/a/b/../c') == '/a/c'\n"
            "    assert candidate('a/../../b') == '/b'\n"
            "    assert candidate('/') == '/'\n"
        ),
        entry_point=entry,
        suite="controlled_context",
        metadata={"family": "normalize_path", "difficulty_seed": rng.randint(0, 10_000)},
    )


def _controlled_context(entry_point: str, target_tokens: int, rng: random.Random) -> str:
    blocks: list[str] = []
    used = 0
    block_id = 0
    while used < target_tokens:
        name = f"legacy_helper_{block_id}_{rng.randint(100, 999)}"
        block = (
            "# --- archived repository context ---\n"
            f"# Module note: {entry_point} is referenced in planning docs but implemented elsewhere.\n"
            f"def {name}(items):\n"
            "    \"\"\"Legacy helper retained for compatibility tests.\"\"\"\n"
            "    total = 0\n"
            "    for item in items:\n"
            "        if isinstance(item, int) and item % 2 == 0:\n"
            "            total += item\n"
            "    return total\n\n"
            "# CI note: do not depend on network, file system, or wall clock state.\n"
            "# Error handbook: ValueError usually means malformed historical data.\n"
            "# --- end archived context ---\n\n"
        )
        blocks.append(block)
        used += count_tokens(block)
        block_id += 1
    return "".join(blocks)


# ---------------------------------------------------------------------------
# SWE-bench Lite (optional; needs the `datasets` install + network)
# ---------------------------------------------------------------------------
def load_swebench_lite(n: Optional[int] = None) -> list[Task]:
    """Load SWE-bench Lite (Jimenez et al. 2024). Optional: returns [] gracefully
    if the dataset is unavailable so the rest of the suite still runs."""
    try:
        from datasets import load_dataset  # type: ignore
        ds = load_dataset("princeton-nlp/SWE-bench_Lite", split="test")
    except Exception:
        return []
    out: list[Task] = []
    items = ds if n is None else ds.select(range(min(n, len(ds))))
    for r in items:
        out.append(
            Task(
                task_id=r["instance_id"],
                prompt=r.get("problem_statement", "")[:8000],
                context=r.get("hints_text", "") or "",
                # SWE-bench evaluation is heavy (real repo + container). Here we
                # use a degenerate 'check' that always succeeds; cost/token
                # statistics remain meaningful, but pass@1 will not. Experiments
                # that need real SWE-bench grading should call the upstream
                # harness — see docs/e4.md.
                test_code="def check(_):\n    pass\n",
                entry_point="solve",
                suite="swebench_lite",
                metadata={"raw": {k: r[k] for k in ("instance_id", "repo", "base_commit")}},
            )
        )
    return out


# ---------------------------------------------------------------------------
# Synthetic Tool-Use Suite (defined in §3.2 / Appendix A of the article)
# ---------------------------------------------------------------------------
def build_synthetic_tool_use_suite(n: int = 50, seed: int = 42) -> list[Task]:
    """Procedural generator for the article's Synthetic Tool-Use Suite.

    Each task asks the agent to independently solve k ∈ {2,3,4} fully
    independent subtasks (parallelism degree p_||). Verification is set up so
    the test code checks each sub-result with a separate ``check`` clause —
    this is exactly the regime in which H3 predicts that Classical-MAS wins
    by parallelising sub-roles, while Hybrid-INoT's serial inner loop cannot.
    """
    rng = random.Random(seed)
    tasks: list[Task] = []
    for i in range(n):
        k = rng.choice([2, 3, 4])
        ops: list[tuple[str, int, int]] = []
        for j in range(k):
            a = rng.randint(2, 30)
            b = rng.randint(2, 30)
            op = rng.choice(["add", "mul", "sub"])
            ops.append((op, a, b))
        prompt = (
            "Implement a module exposing the following independent helper functions.\n"
            "Each function MUST be implemented independently from the others.\n"
            "Return the complete Python source defining all functions in one block.\n\n"
        )
        for j, (op, a, b) in enumerate(ops):
            prompt += f"{j+1}. def f{j}() -> int:  # must return {_ref(op, a, b)} = {_apply(op, a, b)}\n"
        # Fake context: large doc string (parallel tools H3 doesn't need long context, but
        # we add a minimal background so token counts are non-degenerate).
        ctx = (
            "# Project documentation\n"
            "# These helpers are used by independent CI jobs; correctness of one\n"
            "# is independent from any other.\n"
        )
        # Test code calls every f0..f{k-1} and asserts on it.
        check_lines = "\n    ".join(
            f"assert candidate.f{j}() == {_apply(op, a, b)}, 'f{j} wrong'"
            for j, (op, a, b) in enumerate(ops)
        )
        test_code = (
            "import types\n"
            "def check(_unused):\n"
            "    candidate = types.SimpleNamespace()\n"
            + "\n".join(f"    candidate.f{j} = f{j}" for j in range(k))
            + f"\n    {check_lines}\n"
        )
        tasks.append(
            Task(
                task_id=f"synthetic/{i:04d}",
                prompt=prompt,
                context=ctx,
                test_code=test_code,
                entry_point="f0",
                suite="synthetic_tools",
                metadata={
                    "parallelism": k,
                    "requires_tool": True,
                    "force_hybrid_internal": True,
                    "ops": ops,
                    "tool_latency_ms": [rng.randint(80, 180) for _ in range(k)],
                },
            )
        )
    return tasks


def _apply(op: str, a: int, b: int) -> int:
    if op == "add":
        return a + b
    if op == "mul":
        return a * b
    return a - b


def _ref(op: str, a: int, b: int) -> str:
    sym = {"add": "+", "mul": "*", "sub": "-"}[op]
    return f"{a} {sym} {b}"
