FROM swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-1606@sha256:67af22e57989f01d55a8e783ce6afeacfecdf439bf3cba65f53eb5f0a311eb3e
RUN /opt/miniconda3/envs/testbed/bin/python -m pip install --no-cache-dir --disable-pip-version-check --no-deps numpy==1.26.4
